title: "Your Name"
email: ""
description: "A simple Jekyll site"
baseurl: ""
url: ""

plugins:
  - jekyll-paginate

# Pagination: number of posts per page for /blog/
paginate: 5
paginate_path: "/blog/page:num/"

# If posts are dated in the future relative to build time, disable publishing them during build
future: true
# Set site timezone (IANA timezone for Melbourne, Australia)
timezone: "Australia/Melbourne"
