title: "Ritchie Caruso"
email: "ritchiecaruso7@gmail.com"
description: "A simple Jekyll site"
baseurl: ""
url: "https://ritchiecaruso.com"

# Syntax highlighting
markdown: kramdown
highlighter: rouge

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag

# Pagination: number of posts per page for /blog/
paginate: 5
paginate_path: "/blog/page:num/"

# Exclude these from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - .jekyll-metadata

# If posts are dated in the future relative to build time, disable publishing them during build
future: false
# Set site timezone (IANA timezone for Melbourne, Australia)
timezone: "Australia/Melbourne"
